### PR TITLE
Add yellowscreen function to assembly fuctions

### PR DESCRIPTION
**Pull request by Bombardier-C-Kram**

### CODE REVIEW

**Review by NotTheUsualYT — CHANGES_REQUESTED** [review]
ARE YOU KIDDING ME. YOU MOVED INTO BX 0x00 INSTEAD OF XORRING IT. I WILL PERSONALLY GRIND UP YOUR FAMILY AND TURN THEM INTO TEX MEX TACOS. SO YOU WILL HAVE TO WATCH AS YOUR FAMILY IS TRANSFORMED INTO AN INSULT TO MEXICO.

**Comment by Bombardier-C-Kram** [comment]
Fine then. If you dont want my changes, then i will simply close my PR.

**Comment by NotTheUsualYT** [comment]
luv u daddy

**Comment by NotTheUsualYT** [comment]
luv u daddy

**Pull request closed without merging**
